### ISSUE TITLE
How do I use GSSAPI without doing a manual kinit?

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [joshinryz/ansible_ldap_inventory#22]
I'd love to run this inventory using GSSAPI and kerberos without having to manually go into the command line and running kinit beforehand.

Is there a way how to do this?

**Comment by joshinryz** [comment]
There are a few ways, but it is best handled by your job scheduler. Ansible Tower supports this, by defining server credentials, but Kerberos credential creating is a function you will have to handle at the job scheduler level. 

https://docs.ansible.com/ansible-tower/latest/html/administration/kerberos_auth.html

Further, if you are going to SSH into something and run Ansible, you can delegate your credentials to the box from windows. (something we do)

With openssh you can delegate with the `-K` option. You can also set an option in your config file for `GSSAPIDelegateCredentials yes`

Hope that helps.

**Comment by BrandonALXEllisSS** [comment]
Err, correct me if I'm wrong, but these credentials only seem to be handled when you're connecting to a remote host. Using this plugin only does stuff on the localhost.

I guess you could do a win-ping to a domain controller to establish the kinit beforehand and then call this plugin as part of a job schedule, BUT, if the [documentation ](https://docs.ansible.com/ansible-tower/latest/html/administration/kerberos_auth.html#working-with-kerberos-tickets)that you sent is really being truthful, then the kerberos ticket should *technically* be deleted and such a feat shouldn't be possible: 

> A new ticket is created in a temporary credential cache for each host, before each task executes (to minimize the chance of ticket expiration). The temporary credential caches are **deleted** after each task, and will not interfere with the default credential cache.

This is terrible, but I just snuck these lines of code in and they seem to work for establishing the proper ticket. Let's see how long it holds up...
```
cmd = ['kinit', self.username]
error_code = subprocess.run(cmd, input=self.password.encode(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode
if error_code > 0:
     raise AnsibleError("kinit failure")
```

**Comment by joshinryz** [comment]
@BrandonALXEllisSS - So, what you are experiencing with Kerberos is delegation issues. This really isnt the place for this discussion, but I'm happy to point you in the right direction.

Basically, when you authenticate with kerberos you get a TGT (ticket granting ticket), you use this ticket in order to receive a TGS (ticket granting service) - such as accessing network shares, etc. However, when you use GSSAPI in order to connect to a Linux host (say over ssh), by default you can not DELEGATE your TGT to the Linux host. This is known as a double hop restriction.

You can however configure exceptions  in Active Directory, or create a TGT on the linux host by using a username / password and having something such as SSSD configured properly. 

A good place to understand all this is Steve Syfus Blog: https://syfuhs.net/understanding-identity-delegation

Or Jordan's Ansible presentations: https://www.ansible.com/hubfs//AnsibleFest%20ATL%20Slide%20Decks/AnsibleFest%202019%20-%20Me,%20Myself,%20and%20System.pdf

God speed and good luck
